"""empty message

Revision ID: 091130814e36
Revises: b844ea80f1dc
Create Date: 2024-12-28 15:54:05.427040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091130814e36'
down_revision = 'b844ea80f1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
