"""Update Character model

Revision ID: 5d9f6941b9e4
Revises: 07c039da27a8
Create Date: 2024-12-28 15:31:10.443317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9f6941b9e4'
down_revision = '07c039da27a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('house',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('animal',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('death',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('strength',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('strength',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('death',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('animal',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('house',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
