"""empty message

Revision ID: b844ea80f1dc
Revises: 5d9f6941b9e4
Create Date: 2024-12-28 15:48:45.953314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b844ea80f1dc'
down_revision = '5d9f6941b9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('house',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('animal',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('death',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('strength',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('strength',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('death',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('animal',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('house',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
